name: IMR Media
slug: imr-media
description: Marketing und Lead-Generierung für IMR Media Agentur
owner: Erik + Julian
created: 2026-02-02

goals:
  - Organische Leads über Reddit generieren
  - Brand Awareness in deutschen Tech/Business Communities
  - Positionierung als E-Commerce Experten

active_strategies:
  - reddit-karma-aufbau
